# Generated by Django 5.2 on 2025-05-07 09:18

import app.models
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(upload_to=app.models.loop_audio_upload_path, validators=[app.models.validate_audio_extension, functools.partial(app.models.validate_fileMB_size, *(), **{'size_MB': 10})])),
                ('cover_image', models.ImageField(upload_to=app.models.loop_cover_upload_path, validators=[app.models.validate_image_extension, app.models.validate_coverimage_size])),
                ('key', models.CharField(blank=True, help_text='Example: C, Dm', max_length=10, null=True)),
                ('bpm', models.PositiveIntegerField(blank=True, help_text='Example: 120, 140', null=True)),
                ('tags', models.CharField(blank=True, help_text='Separate tags with commas', max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('time_signature', models.CharField(blank=True, help_text='Example: 4/4, 3/4', max_length=10, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='defaultProfileImage.jpg', max_length=255, upload_to=app.models.profileimage_upload_path, validators=[app.models.validate_image_extension, app.models.validate_coverimage_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SamplePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('zip_file', models.FileField(upload_to=app.models.samplepack_zip_upload_path, validators=[app.models.validate_zip_extension, functools.partial(app.models.validate_fileMB_size, *(), **{'size_MB': 20})])),
                ('cover_image', models.ImageField(upload_to=app.models.samplepack_cover_upload_path, validators=[app.models.validate_image_extension, app.models.validate_coverimage_size])),
                ('preview_audio', models.FileField(blank=True, default=None, null=True, upload_to=app.models.samplepack_preview_upload_path, validators=[app.models.validate_audio_extension, functools.partial(app.models.validate_fileMB_size, *(), **{'size_MB': 10})])),
                ('tags', models.CharField(blank=True, help_text='Separate tags with commas', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplepacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
