# Generated by Django 5.2 on 2025-04-29 15:01

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(upload_to='loops/', validators=[app.models.validate_audio_extension, app.models.validate_file_size])),
                ('tags', models.CharField(help_text='Separati da virgole', max_length=255)),
                ('bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=10, null=True)),
                ('main_instrument', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(upload_to='loop_covers/', validators=[app.models.validate_image_extension, app.models.validate_cover_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
