# Generated by Django 5.2 on 2025-05-16 14:34

import app.models
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='defaultProfileImage.jpg', max_length=255, upload_to=app.models.profileimage_upload_path, validators=[app.models.validate_image_extension, app.models.validate_coverimage_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SamplePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='', validators=[app.models.validate_image_extension, app.models.validate_coverimage_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('zip_file', models.FileField(upload_to=app.models.samplepack_zip_upload_path, validators=[app.models.validate_zip_extension, functools.partial(app.models.validate_fileMB_size, *(), **{'size_MB': 20})])),
                ('preview_audio', models.FileField(blank=True, null=True, upload_to=app.models.samplepack_preview_upload_path, validators=[app.models.validate_audio_extension, functools.partial(app.models.validate_fileMB_size, *(), **{'size_MB': 10})])),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='items_%(class)s', to='app.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='', validators=[app.models.validate_image_extension, app.models.validate_coverimage_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(upload_to=app.models.loop_audio_upload_path, validators=[app.models.validate_audio_extension, functools.partial(app.models.validate_fileMB_size, *(), **{'size_MB': 10})])),
                ('key', models.CharField(blank=True, choices=[('C Major', 'C Major'), ('C Minor', 'C Minor'), ('C# Major', 'C# Major'), ('C# Minor', 'C# Minor'), ('D Major', 'D Major'), ('D Minor', 'D Minor'), ('D# Major', 'D# Major'), ('D# Minor', 'D# Minor'), ('E Major', 'E Major'), ('E Minor', 'E Minor'), ('F Major', 'F Major'), ('F Minor', 'F Minor'), ('F# Major', 'F# Major'), ('F# Minor', 'F# Minor'), ('G Major', 'G Major'), ('G Minor', 'G Minor'), ('G# Major', 'G# Major'), ('G# Minor', 'G# Minor'), ('A Major', 'A Major'), ('A Minor', 'A Minor'), ('A# Major', 'A# Major'), ('A# Minor', 'A# Minor'), ('B Major', 'B Major'), ('B Minor', 'B Minor')], max_length=10, null=True)),
                ('bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('time_signature_num', models.PositiveIntegerField(blank=True, default=4, null=True)),
                ('time_signature_den', models.PositiveIntegerField(blank=True, default=4, null=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loops', to='app.genre')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='items_%(class)s', to='app.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
