# Generated by Django 5.2 on 2025-04-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loop',
            name='main_instrument',
        ),
        migrations.AddField(
            model_name='loop',
            name='time_signature',
            field=models.CharField(blank=True, help_text='Example: 4/4, 3/4', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='bpm',
            field=models.PositiveIntegerField(blank=True, help_text='Example: 120, 140', null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='key',
            field=models.CharField(blank=True, help_text='Example: C, Dm', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='tags',
            field=models.CharField(help_text='Separate tags with commas', max_length=255),
        ),
    ]
