# Generated by Django 5.2 on 2025-04-30 12:21

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_loop_main_instrument_loop_time_signature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='audio_file',
            field=models.FileField(upload_to=app.models.loop_audio_upload_path, validators=[app.models.validate_audio_extension, app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='loop',
            name='cover_image',
            field=models.ImageField(upload_to=app.models.loop_cover_upload_path, validators=[app.models.validate_image_extension, app.models.validate_coverimage_size]),
        ),
        migrations.AlterField(
            model_name='loop',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='tags',
            field=models.CharField(blank=True, help_text='Separate tags with commas', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SamplePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('zip_file', models.FileField(upload_to=app.models.samplepack_zip_upload_path, validators=[app.models.validate_zip_file])),
                ('cover_image', models.ImageField(upload_to=app.models.samplepack_cover_upload_path, validators=[app.models.validate_image_extension, app.models.validate_coverimage_size])),
                ('preview_audio', models.FileField(upload_to=app.models.samplepack_preview_upload_path, validators=[app.models.validate_audio_extension, app.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplepacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
