# Generated by Django 5.2 on 2025-05-08 12:49

import app.models
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fix_tags_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='bpm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='cover_image',
            field=models.ImageField(upload_to='', validators=[app.models.validate_image_extension, app.models.validate_coverimage_size]),
        ),
        migrations.AlterField(
            model_name='loop',
            name='key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='time_signature',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='samplepack',
            name='cover_image',
            field=models.ImageField(upload_to='', validators=[app.models.validate_image_extension, app.models.validate_coverimage_size]),
        ),
        migrations.AlterField(
            model_name='samplepack',
            name='preview_audio',
            field=models.FileField(blank=True, null=True, upload_to=app.models.samplepack_preview_upload_path, validators=[app.models.validate_audio_extension, functools.partial(app.models.validate_fileMB_size, *(), **{'size_MB': 10})]),
        ),
        migrations.AlterField(
            model_name='samplepack',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='samplepack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
