# Generated by Django 5.2 on 2025-05-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_loop_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='bpm',
            field=models.PositiveIntegerField(blank=True, max_length=3, null=True),
        ),
    ]
