# Generated by Django 5.2 on 2025-05-16 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_loop_bpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='bpm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
