# Generated by Django 5.2 on 2025-05-09 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_like_repost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplepack',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
