# Generated by Django 5.2 on 2025-09-01 09:23

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_loop_bpm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='defaultProfileImage.jpg', max_length=255, upload_to=app.models.profileimage_upload_path, validators=[app.models.validate_image_extension, app.models.validate_coverimage_size])),
                ('bio', models.TextField(blank=True, help_text='Scrivi qualcosa su di te...', max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Username Instagram (senza @)', max_length=100, null=True)),
                ('youtube', models.URLField(blank=True, help_text='Link al tuo canale YouTube', null=True)),
                ('soundcloud', models.URLField(blank=True, help_text='Link al tuo profilo SoundCloud', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
