# Generated by Django 5.2 on 2025-09-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userprofile_delete_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
