# Generated by Django 5.2 on 2025-05-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_text_comment_body_comment_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='title',
        ),
    ]
