# Generated by Django 5.2 on 2025-05-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_name_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
