# Generated by Django 5.2 on 2025-09-08 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_audioplay_ip_address_alter_audioplay_user'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audioplay',
            unique_together={('user', 'content_type', 'object_id', 'ip_address', 'played_at')},
        ),
    ]
