# Generated by Django 5.2 on 2025-05-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comment_likes_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='loop',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='samplepack',
            name='tags',
        ),
        migrations.AddField(
            model_name='loop',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items_%(class)s', to='app.tag'),
        ),
        migrations.AddField(
            model_name='samplepack',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items_%(class)s', to='app.tag'),
        ),
    ]
