# Generated by Django 5.2 on 2025-09-08 15:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_audioplay_unique_together'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audioplay',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
