# Generated by Django 5.2 on 2025-09-09 07:54

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_audioplay_unique_together'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audioplay',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='audioplay',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='audioplay',
            constraint=models.UniqueConstraint(condition=models.Q(('user', None), _negated=True), fields=('user', 'content_type', 'object_id', 'date'), name='unique_play_per_user_per_day'),
        ),
        migrations.AddConstraint(
            model_name='audioplay',
            constraint=models.UniqueConstraint(condition=models.Q(('user', None)), fields=('ip_address', 'content_type', 'object_id', 'date'), name='unique_play_per_ip_per_day'),
        ),
    ]
