# Generated by Django 6.0.4 on 2026-04-24 11:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_audioplay_unique_together_audioplay_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='cover_image',
            field=models.ImageField(upload_to='temp/', validators=[app.models.validate_image_extension, app.models.validate_coverimage_size]),
        ),
        migrations.AlterField(
            model_name='samplepack',
            name='cover_image',
            field=models.ImageField(upload_to='temp/', validators=[app.models.validate_image_extension, app.models.validate_coverimage_size]),
        ),
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
